### ISSUE TITLE
schema registry 추가

### ISSUE THREAD

**Issue by jaegwonseo** [myrealtrip/mrt-dp-kafka-center#5]
connect와 동일한 방식으로 작업 대신 프론트에 스키마 레지스트리 버튼 생성 필요함

**Comment by jaegwonseo** [comment]
프론트를 바꿔야 하기 때문에 아래와 같이 프론트 디렉토리에 들어가서 빌드 실행
```
npm install --save react-router
npm install --save loadable-components

npm install
npm audit fix --force
npm run build
```


에러 발생
```
> @xaecbd/kafka-center-frontends@0.1.0 build
> icejs build

ice.js 2.2.1

The build-plugin-ice-auth has been built in. Please remove it from build.json.

info 使用 Fusion 组件主题包： @alifd/theme-design-pro
ERR! CONFIG Failed to get config.
ERR! apply unknown method addTemplateDir
Error: apply unknown method addTemplateDir
    at BuildService.Context.applyMethod (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-scripts/lib/core/Context.js:254:23)
    at applyMethod (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-scripts/lib/core/Context.js:369:33)
    at /Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-plugin-ice-auth/lib/index.js:48:13
    at step (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-plugin-ice-auth/lib/index.js:33:23)
    at Object.next (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-plugin-ice-auth/lib/index.js:14:53)
    at /Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-plugin-ice-auth/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-plugin-ice-auth/lib/index.js:4:12)
    at default_1 (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-plugin-ice-auth/lib/index.js:42:12)
    at BuildService.<anonymous> (/Users/jaegwon.seo/workspace/mrt-dp-kafka-center/KafkaCenter-Frontend/node_modules/build-scripts/lib/core/Context.js:394:23)
```

**Comment by jaegwonseo** [comment]
package.json에 빠진 npm 의존성 추가후 빌드 완료
npm install               : package.json의 의존성 설치             
npm run build          : package.json 의  scripts.build(icejs build) 실행

**Comment by jaegwonseo** [comment]
schema registry 추가 완료
![스크린샷 2021-11-21 오후 6 02 08](https://user-images.githubusercontent.com/90180644/142756050-3099bacc-80ac-44c6-9462-219c43b5979f.png)
